---
- name: Pull Docker Image from Docker Hub
  hosts: localhost
  connection: local
  become: false
  tasks:

    - name: Pull Docker Image
      community.docker.docker_image:
        name: "girish445g/calculator"
        source: pull
      enviroment:
        DOCKER_HOST: "unix:///var/run/docker.sock"

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result

    - name: Start Docker service
      service:
        name: docker
        state: started

    - name: Running container
      shell: docker run -it -d --name calculator girish445g/calculator /bin/bash
