---
- name: Pull Docker Image from Docker Hub
  hosts: localhost
  remote_user: girish
  become: true
  tasks:
    - name: Pull Docker Image
      community.docker.docker_image:
        name: "girish445g/calculator"
        source: pull
        register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result

    - name: Start Docker service
      service:
        name: docker
        state: started

    - name: Run container
      shell: docker run -it -d --name calculator girish445g/calculator /bin/bash
